### ISSUE TITLE
more liquidity in the uniswap pool

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/improvements-and-bugs#2]
### ⚡️ Challenge:
Liquidity is low and more is needed to be added.

### 🦋 Desired Outcome
Lots and lots of liquidity to reduce slippage. Ideas have been brought up here: https://discord.com/channels/768756174433943554/819857483739824168/821004091391606786

### 🎯 Action Points:
adding liquidity to the ETH-UNI v2 pool

### 🐇 Additional Information
it is planned to acquire more liquidity in June due to the release of more HBT.

**Comment by ghost** [comment]
**Follow-up proposals are here:**
linear solution:
https://github.com/0xHabitat/improvements-and-bugs/issues/6
quadratic solution:
https://github.com/0xHabitat/improvements-and-bugs/issues/4
