### ISSUE TITLE
solved - Missing HBT after Liquidity Mining

### ISSUE THREAD

**Issue by TheChrisOwl** [0xHabitat/improvements-and-bugs#28]
**Describe the bug**
I had purchased 1,128.4633207306 HBT (0x5a4f64377691d4b8a0c1852388e75b89f3b84323ef747b9da1208a6fa69bad0e)
and then delegated it during Round 1 Liquidity Pool (https://0xhabitat.org/lp/)
- approved spending limit (0x2812a396a16f70bfed7d51aa31171245ece2ac3e38ab4aa5fb03874ff19e0730)
- added liquidity (0x807f4ad4f1c5faedc83ddca3e5a20e6e3f5150a232e2c7b9e9cb94e4aabcaf5d)

and then I added in more in Round 2 Liquidity Pool (0x2351e25bfe7034930b856a4a15fba835d98d570caca15ed4f89527093c6cf3eb)

I have no idea where my HBT is now, how do I get it back? 
I'd like the HBT sent to my wallet: 0x71553076302fe2E1E6faeA338446DF492Fd0bC35

I have this token called Token Uniswap V2 which I don't know what to do with, is that where the HBT is?

I tried to swap it on Metamask and it did not work, it says: No quotes available.
I tried to swap it on Uniswap and it won't pull up the Uniswap V2 coin.

**To Reproduce**

**Expected behavior**
I expected I would get a greater amount of HBT than I put in. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Smartphone (please complete the following information):**

**Additional context**

All wallet history (8 transactions) https://etherscan.io/address/0x71553076302fe2e1e6faea338446df492fd0bc35

**Comment by pinkiebell** [comment]
👋 You can remove lp positions via 

https://app.uniswap.org/#/remove/v2/0x0ace32f6e87ac1457a5385f8eb0208f37263b415/ETH
